# Normalize and encode
último paso en el preprocesamiento de datos. Se distinguen las variables continuas y las categóricas. Las primeras se las normaliza usando StandardScaler de sklearn, método que elimina la media y luego normaliza la varianza. A las últimas mencionadas se les codifica la etiqueta con LabelEncoder de sklearn para poder manejar los datos de forma más práctica. Los dos archivos resultantes que salgan de este cuaderno son los que se usarán ya para entrenar al modelo.

In [25]:
import pandas as pd
import numpy as np
from pandas_summary import DataFrameSummary
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [26]:
# pip install pyarrow

In [27]:
PATH = "/kaggle/input/rossman-durations/"
df_train = pd.read_feather(PATH+'all_preprocessed_train.fth')
df_test = pd.read_feather(PATH+'all_preprocessed_test.fth')

In [28]:
df_train.shape, df_test.shape

((1017209, 81), (41088, 80))

In [29]:
# Verificación de que se hicieron bien las cosas en testa también
set(df_train.columns) - set(df_test.columns)

{'Customers', 'Sales'}

In [30]:
(df_train['CompetitionDistance'].isna()).sum()

0

# Variables "categóricas"
Aquellas cuya información puede representarse mediante un conjunto finito y enumerable de posibilidades

In [31]:
cat_vars = ['Store', 'DayOfWeek', 'Year', 'Month', 'Day', 'StateHoliday', 
            'CompetitionMonthsOpen', 'Promo2Weeks', 
            'StoreType', 'Assortment', 'PromoInterval', 
            'CompetitionOpenSinceYear', 'Promo2SinceYear', 
            'State', 'Week', 'Events', 'Promo_fw', 'Promo_bw', 
            'StateHoliday_bool_fw', 'StateHoliday_bool_bw', 'SchoolHoliday_fw', 
            'SchoolHoliday_bw']

In [32]:
df_train[cat_vars]

,Store,DayOfWeek,Year,Month,Day,StateHoliday,CompetitionMonthsOpen,Promo2Weeks,StoreType,Assortment,...,Promo2SinceYear,State,Week,Events,Promo_fw,Promo_bw,StateHoliday_bool_fw,StateHoliday_bool_bw,SchoolHoliday_fw,SchoolHoliday_bw
0,1,5,2015,7,31,0,24,25,c,a,...,1990,HE,31,Fog,1.0,5.0,0.0,0.0,1.0,5.0
1,2,5,2015,7,31,0,24,25,a,a,...,2010,TH,31,Fog,1.0,5.0,0.0,0.0,1.0,5.0
2,3,5,2015,7,31,0,24,25,a,a,...,2011,NW,31,Fog,1.0,5.0,0.0,0.0,1.0,5.0
3,4,5,2015,7,31,0,24,25,c,c,...,1990,BE,31,Sunny,1.0,5.0,0.0,0.0,1.0,5.0
4,5,5,2015,7,31,0,3,25,a,a,...,1990,SN,31,Sunny,1.0,5.0,0.0,0.0,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013,1,1,a,0,0,a,a,...,2013,NW,1,Rain,1.0,0.0,1.0,1.0,4.0,1.0
1017205,1112,2,2013,1,1,a,24,25,c,c,...,1990,NW,1,Rain,1.0,0.0,1.0,1.0,4.0,1.0
1017206,1113,2,2013,1,1,a,24,25,a,c,...,1990,SH,1,Rain,1.0,0.0,1.0,1.0,4.0,1.0
1017207,1114,2,2013,1,1,a,24,25,a,c,...,1990,HH,1,Rain,1.0,0.0,1.0,1.0,4.0,1.0
1017208,1115,2,2013,1,1,a,24,25,d,c,...,2012,HE,1,Rain,1.0,0.0,1.0,1.0,7.0,1.0

In [33]:
df_train.StateHoliday.iloc[0]

'0'

In [34]:
#DataFrameSummary(df_train[cat_vars]).summary()

In [35]:
df_train[cat_vars].describe()

,Store,DayOfWeek,Year,Month,Day,CompetitionMonthsOpen,Promo2Weeks,CompetitionOpenSinceYear,Promo2SinceYear,Week,Promo_fw,Promo_bw,StateHoliday_bool_fw,StateHoliday_bool_bw,SchoolHoliday_fw,SchoolHoliday_bw
count,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1017209.0,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06
mean,5.584297e+02,3.998341e+00,2.013832e+03,5.846762e+00,1.570279e+01,2.020750e+01,2.286060e+01,2.002843e+03,2.000889e+03,23.615515,2.670601e+00,2.648679e+00,2.067982e-01,2.136729e-01,1.230985e+00,1.232767e+00
std,3.219087e+02,1.997391e+00,7.773960e-01,3.326097e+00,8.787638e+00,7.959786e+00,6.723693e+00,9.540569e+00,1.093983e+01,14.433381,1.902708e+00,1.910292e+00,4.706608e-01,4.755137e-01,2.055302e+00,2.053886e+00
min,1.000000e+00,1.000000e+00,2.013000e+03,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.990000e+03,1.990000e+03,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.800000e+02,2.000000e+00,2.013000e+03,3.000000e+00,8.000000e+00,2.400000e+01,2.500000e+01,1.990000e+03,1.990000e+03,11.0,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,5.580000e+02,4.000000e+00,2.014000e+03,6.000000e+00,1.600000e+01,2.400000e+01,2.500000e+01,2.006000e+03,2.009000e+03,22.0,3.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,8.380000e+02,6.000000e+00,2.014000e+03,8.000000e+00,2.300000e+01,2.400000e+01,2.500000e+01,2.011000e+03,2.012000e+03,35.0,5.000000e+00,5.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,2.000000e+00
max,1.115000e+03,7.000000e+00,2.015000e+03,1.200000e+01,3.100000e+01,2.400000e+01,2.500000e+01,2.015000e+03,2.015000e+03,52.0,5.000000e+00,5.000000e+00,2.000000e+00,2.000000e+00,7.000000e+00,7.000000e+00

In [36]:
# Reemplaza nulls por "" en categoricas
# for v in cat_vars: df_train.loc[df_train[v].isnull(), v] = ""

In [37]:
# for v in cat_vars: df_test.loc[df_test[v].isnull(), v] = ""

# Variables continuas

In [38]:
df_train.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday', 'Year', 'Month', 'Week', 'Day',
       'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval',
       'CompetitionOpenSince', 'Promo2Since', 'State', 'file', 'week', 'trend',
       'Date_y', 'Month_y', 'Day_y', 'file_DE', 'week_DE', 'trend_DE',
       'Date_DE', 'State_DE', 'Month_DE', 'Day_DE', 'file_y',
       'Max_TemperatureC', 'Mean_TemperatureC', 'Min_TemperatureC',
       'Dew_PointC', 'MeanDew_PointC', 'Min_DewpointC', 'Max_Humidity',
       'Mean_Humidity', 'Min_Humidity', 'Max_Sea_Level_PressurehPa',
       'Mean_Sea_Level_PressurehPa', 'Min_Sea_Level_PressurehPa',
       'Max_VisibilityKm', 'Mean_VisibilityKm', 'Min_VisibilitykM',
       'Max_Wind_SpeedKm_h', 'Mean_Wind_SpeedKm_h', 'Max_Gust_SpeedKm_h',
       'Precipitationmm', 'CloudCover', 'Events', 'WindDirDegrees',
       'StateName', 'Year_y', 'Week_y', 'CompetitionDaysOpen',
       'CompetitionMonthsOpen', 'Promo2Days', 'Promo2Weeks',
       'StateHoliday_bool', 'AfterSchoolHoliday', 'BeforeSchoolHoliday',
       'AfterStateHoliday_bool', 'BeforeStateHoliday_bool', 'AfterPromo',
       'BeforePromo', 'SchoolHoliday_bw', 'StateHoliday_bool_bw', 'Promo_bw',
       'SchoolHoliday_fw', 'StateHoliday_bool_fw', 'Promo_fw'],
      dtype='object')

In [39]:
contin_vars = ['CompetitionDistance', 
               'Max_TemperatureC', 'Mean_TemperatureC', 'Min_TemperatureC', 
               'Precipitationmm', 'Max_Humidity', 'Mean_Humidity', 'Min_Humidity', 
               'Max_Wind_SpeedKm_h', 'Mean_Wind_SpeedKm_h', 'CloudCover', 'trend', 
               'trend_DE', 'AfterStateHoliday_bool', 'BeforeStateHoliday_bool', 
               'Promo', 'SchoolHoliday', 'StateHoliday_bool']

In [40]:
DataFrameSummary(df_train[contin_vars]).summary().loc[['uniques', 'types', 'missing']].T

                        uniques    types missing
CompetitionDistance         654  numeric       0
Max_TemperatureC             50  numeric       0
Mean_TemperatureC            45  numeric       0
Min_TemperatureC             40  numeric       0
Precipitationmm              40  numeric       0
Max_Humidity                 52  numeric       0
Mean_Humidity                71  numeric       0
Min_Humidity                 93  numeric       0
Max_Wind_SpeedKm_h           42  numeric       0
Mean_Wind_SpeedKm_h          27  numeric       0
CloudCover                    9  numeric       0
trend                        67  numeric       0
trend_DE                     38  numeric       0
AfterStateHoliday_bool      136  numeric       0
BeforeStateHoliday_bool     147  numeric       0
Promo                         2     bool       0
SchoolHoliday                 2     bool       0
StateHoliday_bool             2     bool       0

In [41]:
# Reemplaza nulls por 0 en continuas
# for v in contin_vars: df_train.loc[df_train[v].isnull(), v] = 0
# for v in contin_vars: df_test.loc[df_test[v].isnull(), v] = 0

# Normalización en continuas y LabelEncode en Categoricas

In [42]:
from sklearn_pandas import DataFrameMapper

In [43]:
cat_maps = [(o, LabelEncoder()) for o in cat_vars]
contin_maps = [([o], StandardScaler()) for o in contin_vars]

In [44]:
mapper_cat = DataFrameMapper(cat_maps)
_ = mapper_cat.fit(df_train)

In [45]:
# Assortment es la novena posición en cat_maps
N = 10
print(list(zip(df_train['Assortment'].values[:N], mapper_cat.transform(df_train)[:,9][:N])))
print(list(zip(df_train['Events'].values[:N], mapper_cat.transform(df_train)[:,15][:N])))
print(list(zip(df_train['Year'].values[:N], mapper_cat.transform(df_train)[:,2][:N])))

[('a', 0), ('a', 0), ('a', 0), ('c', 2), ('a', 0), ('a', 0), ('c', 2), ('a', 0), ('c', 2), ('a', 0)]
[('Fog', 0), ('Fog', 0), ('Fog', 0), ('Sunny', 20), ('Sunny', 20), ('Sunny', 20), ('Rain', 10), ('Rain', 10), ('Fog', 0), ('Sunny', 20)]
[(2015, 2), (2015, 2), (2015, 2), (2015, 2), (2015, 2), (2015, 2), (2015, 2), (2015, 2), (2015, 2), (2015, 2)]

In [46]:
mapper_cont = DataFrameMapper(contin_maps)
_ = mapper_cont.fit(df_train)

In [47]:
N = 10
print(df_train['CompetitionDistance'].values[:N])
print(mapper_cont.transform(df_train)[:, 0][:N])

[ 1270.   570. 14130.   620. 29910.   310. 24000.  7520.  2030.  3160.]
[-0.51104292 -0.59341201  1.00219483 -0.5875285   2.85902934 -0.62400624
  2.16359893  0.22439533 -0.42161363 -0.28864639]

In [48]:
# La hacemos con todas ahora
df_train[cat_vars] = mapper_cat.transform(df_train)
df_test[cat_vars] = mapper_cat.transform(df_test)

In [49]:
df_train[contin_vars] = mapper_cont.transform(df_train)
df_test[contin_vars] = mapper_cont.transform(df_test)

In [50]:
df_train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,Year,...,AfterStateHoliday_bool,BeforeStateHoliday_bool,AfterPromo,BeforePromo,SchoolHoliday_bw,StateHoliday_bool_bw,Promo_bw,SchoolHoliday_fw,StateHoliday_bool_fw,Promo_fw
0,0,4,2015-07-31,5263,555,1,1.273237,0,2.144211,2,...,0.644376,1.072424,0,0,5,0,5,1,0,1
1,1,4,2015-07-31,6064,625,1,1.273237,0,2.144211,2,...,0.965073,1.072424,0,0,5,0,5,1,0,1
2,2,4,2015-07-31,8314,821,1,1.273237,0,2.144211,2,...,0.644376,1.072424,0,0,5,0,5,1,0,1
3,3,4,2015-07-31,13995,1498,1,1.273237,0,2.144211,2,...,0.965073,1.072424,0,0,5,0,5,1,0,1
4,4,4,2015-07-31,4822,559,1,1.273237,0,2.144211,2,...,0.644376,1.072424,0,0,5,0,5,1,0,1

In [51]:
DataFrameSummary(df_train[cat_vars]).summary().loc[['uniques', 'types']]

,Store,DayOfWeek,Year,Month,Day,StateHoliday,CompetitionMonthsOpen,Promo2Weeks,StoreType,Assortment,...,Promo2SinceYear,State,Week,Events,Promo_fw,Promo_bw,StateHoliday_bool_fw,StateHoliday_bool_bw,SchoolHoliday_fw,SchoolHoliday_bw
uniques,1115,7,3,12,31,4,25,26,4,3,...,8,12,52,22,6,6,3,3,8,8
types,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,...,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric

# Final processing

In [52]:
df_train.shape

(1017209, 81)

In [53]:
df_sales = df_train[df_train.Sales!=0]

In [54]:
df_sales.shape

(844338, 81)

In [55]:
df_test.reset_index(inplace=True)

In [56]:
df_sales.reset_index(inplace=True)

In [57]:
df_sales.to_feather('train_normalized_data.fth')

In [58]:
df_test.to_feather('test_normalized_data.fth')

In [59]:
(df_test['Open'] == 0).sum()

5984

In [60]:
(df_sales['Open'] == 0).sum()

0

In [61]:
(df_train['CompetitionDistance'].isna()).sum()

0